### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by tribhuwan1123** [bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date#13]
return statement is throuwing NPE
  public int getFirstWeekDayMonth(@IntRange(from = 1970, to = 2090) int yy, @IntRange(from = 1, to = 12) int mm) {
        return startWeekDayMonthMap.get(yy)[mm];
    }

**Comment by bahadurbaniya** [comment]
I don't see this code in repo.

do you want to write unit test to prove this one in your forked project .

or 

Steps to replicate from 
http://softwaretestingfundamentals.com/defect-report/ would be helful

**Comment by tribhuwan1123** [comment]
The value of the year is starting from 1969.How does that happen ? It was
working fine until yesterday. But suddenly the exception occurred.

**Comment by bahadurbaniya** [comment]
which date conversion is not working? 
ad to bs or bs to ad?

**Comment by bahadurbaniya** [comment]
https://github.com/bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date/blob/master/src/test/java/np/com/bahadur/converter/date/nepali/DateConverterTest.java . Unit test can be added here

**Comment by bahadurbaniya** [comment]
Have not got proper steps to reproduce so closing it. Please raise again with "Steps to reproduce". 
https://github.com/bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date/blob/master/CONTRIBUTING.adoc#raising-bug
