### ISSUE TITLE
Converter bug

### ISSUE THREAD

**Issue by asminzz** [bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date#14]
There's a problem in feb-12-1997 which is supposed to be falgun 1st 2053. but shows magh-30-2053 which does not exist.
After this, half of the february is messed up while converting from ad to bs

**Comment by bahadurbaniya** [comment]
Thank you for reporting bug. I am having a look. Hopefully fixed in couple of days.

**Comment by bahadurbaniya** [comment]
This is fixed.  

np/com/bahadur/converter/date/nepali/DateConverterTest.java:55 has a test to verify fix. 


  @Test
    void testAdToBsBugFix() throws ParseException {
//12 Feb 1997 - 1 Falgun 2053  --- error giving 2053 Magh 30
        assertEquals("2053-11-1", dc.convertAdToBs("12-02-1997"));
    }

Above test is passing.

**Comment by bahadurbaniya** [comment]
New package with fix https://github.com/bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date/packages/123720  

if you are using Maven
