### ISSUE TITLE
Maven Build Error HTTPS Required

### ISSUE THREAD

**Issue by Paawan12** [bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date#16]
Effective January 15, 2020, The Maven Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

Currently "HTTPS Required" error is coming while performing clean and build in netbeans.

To Fix this error we have to add following code in pom.xml before of `</project>` tag.

`<repositories>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>`

**Comment by bahadurbaniya** [comment]
Hi @Paawan12 ,  thanks for reporting. can you please attach log messages of error/warn?  if you would like you can create pull request? --thanks
