### ISSUE TITLE
Wrong Conversion

### ISSUE THREAD

**Issue by bhusalb** [bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date#9]
Please check for 1981-10-17 AD date. The expected converted date is 2038-07-01, though output was 2038-07-02.

**Comment by bahadurbaniya** [comment]
np.com.bahadur.converter.date.nepali.DateConverterTest#testAdToBsBug please run this test it gives correct output 

    // २०३८ कार्तिक १ - 1981 October 17

AD 17-10-1981 = BS 2038-7-1
